# Generated by Django 4.0.5 on 2022-07-20 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='categorys',
        ),
    ]
