# Generated by Django 4.0.5 on 2022-07-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_rename_categorys_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categorys', 'verbose_name_plural': 'Categories'},
        ),
    ]
