# Generated by Django 4.0.5 on 2022-07-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Slug',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='ABC', max_length=200, unique=True),
        ),
    ]
